### DISCUSSION TITLE
How to set Table's header?

### DISCUSSION THREAD

**Discussion by dlyltm** [BlazorComponent/MASA.Blazor#1473] [Q&A] [answered]
How to set the background color of the header, vertically center the font, and draw the vertical separation line?

**Comment by capdiem** [comment]
@dlyltm 

- Set bgcolor of the header:
  ```razor
  <MDataTable HeaderProps="@(new Dictionary<string, object>(){ { "Class", "custom-header-css"} })"></MDataTable>
  ```
  
  ``` css
  .custom-header-css {
    background-color: pink;
  }
  ```
- vertically center the font
  I think it's already vertical center in the header th.
- draw the vertical separation line
  I don't understand. Do you what something like `<table>`?
  ![image](https://github.com/masastack/MASA.Blazor/assets/16507773/489d9657-36c6-4f63-b780-b089feef3c59)

**Reply by dlyltm** [reply]
Thank you for your answer.
What I see is that the texts are on the top.The vertical separation line in the header is not displayed.

**Reply by capdiem** [reply, marked as answer]
@dlyltm All your problems can be solved with CSS. If all your datatable are the same UI, you can set the CSS settings globally:
```css
/* set background color of header */
.m-data-table-header {
    background-color: pink;
}

/* add right border to th and td */
.m-data-table th, .m-data-table td {
  border-right: thin solid rgba(0,0,0,.12);
}

.m-data-table th:last-child, .m-data-table td:last-child {
    border-right: none;
}
```

> vertically center the font. What I see is that the texts are on the top.

Can you provide UI screenshots?
