### ISSUE TITLE
Miss scrollbar style when 'Virtual scroller' in 'Dialog'.

### ISSUE THREAD

**Issue by jim-jiang-github** [BlazorComponent/MASA.Blazor#590]
![(5@($G})I}5CLW(IJ0{A@25](https://user-images.githubusercontent.com/29189410/181516794-4eb4a081-1217-4c84-9aec-e53e517745bb.png)

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
The style of the scroll bar on our official website is customized by our document project and has nothing to do with the component style. You need to add the same style to your own project.
``` css
/*scrollbar*/
::-webkit-scrollbar-track {
    border-radius: 15px;
    margin: 5px 0;
}

::-webkit-scrollbar {
    width: 5px;
    height: 5px;
    margin: 5px 0;
}

::-webkit-scrollbar-thumb {
    margin: 5px 0;
    border-radius: 15px;
    background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.44, rgb(170 168 168)), color-stop(0.72, rgb(170 168 168)), color-stop(0.86, rgb(170 168 168)));
}
```
