### ISSUE TITLE
Toast content auto wrap by input string '\r\n'

### ISSUE THREAD

**Issue by jim-jiang-github** [BlazorComponent/MASA.Blazor#614]
![image](https://user-images.githubusercontent.com/29189410/184536739-456d437a-7cfa-4fce-8c92-7cae0b3506cc.png)

Toast content should auto wrap by input string '\r\n', Right?

**Comment by capdiem** [comment]
``` css
.m-toast-detail {
  white-space: pre;
}
```
